name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'  # Каждые 4 часа
  workflow_dispatch:        # Ручной запуск через Actions

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Fetch Telegram News
        run: |
          npm install axios cheerio
          node scripts/fetch-news.js
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add news.json
          git commit -m "Update news cache [skip ci]"
          git push
