name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'  # Каждые 4 часа (в 00:00, 04:00, 08:00 и т.д.)
  workflow_dispatch:       # Ручной запуск

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Права на запись в репозиторий

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install axios cheerio

      - name: Fetch fresh data
        run: |
          node scripts/fetch-news.js
          echo "Последнее обновление: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add news.json
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date -u '+%Y-%m-%d %H:%M UTC')"
          
      - name: Push changes
        run: |
          git pull --rebase origin main
          git push origin main

      - name: Debug info
        if: always()
        run: |
          echo "=== Статус репозитория ==="
          git status
          echo "=== Содержимое news.json ==="
          jq '.' news.json || cat news.json
