name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Fetch and save news
        run: node scripts/fetch-news.js

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          
          # Принудительно обновляем ветку перед коммитом
          git fetch origin
          git reset --hard origin/main
          
          git add news.json
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date -u '+%Y-%m-%d %H:%M UTC')"

      - name: Push changes
        run: |
          git pull origin main --ff-only 2>/dev/null || true
          git push origin main

      - name: Verify result
        run: |
          echo "Последний коммит:"
          git log -1 --oneline
