name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'  # Запуск каждые 4 часа
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Fetch Telegram news
        run: node scripts/fetch-news.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          
          # Обязательные настройки для корректной работы
          git config --global pull.rebase true
          git config --global advice.detachedHead false
          
          # Синхронизация с веткой main
          git pull origin main
          
          # Добавление изменений
          git add news.json
          
          # Коммит и пуш
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update news [skip ci]"
            git push origin HEAD:main
          fi
