name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'  # Запуск каждые 4 часа
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ''  # Явно отключаем кэширование

      - name: Create minimal package.json
        run: |
          echo '{
            "name": "telegram-news-updater",
            "version": "1.0.0",
            "private": true,
            "dependencies": {
              "axios": "^1.8.0",
              "cheerio": "^1.0.0-rc.12"
            }
          }' > package.json

      - name: Install dependencies
        run: |
          # Явно отключаем создание lock-файла
          npm config set package-lock false
          npm install

      - name: Fetch Telegram news
        run: node scripts/fetch-news.js

      - name: Upload debug files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-files
          path: |
            debug.html
            error.txt
            news.json

      - name: Cleanup dependencies
        run: |
          rm -rf node_modules
          rm package.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          git config --global pull.rebase true
          
          git fetch origin
          git reset --hard origin/main
          git add news.json
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update news [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
