name: Update Telegram News

on:
  schedule:
    - cron: '0 */6 * * *' # Каждые 6 часов
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Fetch and save news
        run: node scripts/fetch-news.js
        timeout-minutes: 8
        
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Verify news.json
        run: |
          if [ ! -f "news.json" ]; then
            echo "❌ news.json not found!"
            exit 1
          fi
          echo "✅ news.json exists"
          echo "Size: $(wc -c < news.json) bytes"
          echo "Last updated: $(jq -r '.lastUpdated' news.json)"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add news.json
          # Создаем коммит только если есть изменения
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update news [skip ci]"
          fi

      - name: Pull latest changes
        run: |
          # Сбрасываем любые незакоммиченные изменения
          git reset --hard
          git clean -fd
          # Получаем последние изменения
          git pull origin main

      - name: Push changes
        run: git push origin main

      - name: Upload debug files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-files
          path: |
            news.json
            error.log
