name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Fetch and save news
        run: node scripts/fetch-news.js

      - name: Verify news.json
        run: |
          if [ ! -f "news.json" ]; then
            echo "❌ news.json не найден!"
            exit 1
          fi
          echo "✅ news.json существует"
          echo "Размер: $(wc -c < news.json) байт"
          echo "Последнее обновление: $(jq -r '.lastUpdated' news.json)"

      - name: Verify posts count
        run: |
          COUNT=$(jq '.posts | length' news.json)
          if [ $COUNT -eq 0 ]; then
            echo "❌ Нет постов!"
            exit 1
          fi
          echo "✅ Количество постов: $COUNT"

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add news.json
          
          if git diff-index --quiet HEAD --; then
            echo "Нет изменений для коммита"
          else
            git commit -m "Auto-update news [skip ci]"
            git push
          fi

      - name: Upload debug files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-files
          path: |
            news.json
            error.log
          retention-days: 3
