name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Убрана опция cache, так как нет lock-файла

      - name: Install dependencies
        run: npm install axios --no-package-lock

      - name: Fetch and save news
        run: node scripts/fetch-news.js

      - name: Verify news.json
        run: |
          if [ ! -f "news.json" ]; then
            echo "❌ news.json not found!"
            exit 1
          fi
          echo "✅ news.json exists"
          echo "Size: $(wc -c < news.json) bytes"
          echo "Last updated: $(jq -r '.lastUpdated' news.json)"

      - name: Verify posts count
        run: |
          COUNT=$(jq '.posts | length' news.json)
          if [ $COUNT -ne 7 ]; then
            echo "❌ Expected 7 posts, got $COUNT"
            exit 1
          fi
          echo "✅ Posts count: $COUNT"

      - name: Verify posts recency
        run: |
          CURRENT_TS=$(date +%s)
          LAST_POST_TS=$(date -d "$(jq -r '.lastUpdated' news.json)" +%s)
          DIFF_DAYS=$(( (CURRENT_TS - LAST_POST_TS) / 86400 ))
          
          if [ $DIFF_DAYS -gt 2 ]; then
            echo "❌ Posts are outdated! Last update was $DIFF_DAYS days ago"
            exit 1
          fi
          echo "✅ Posts are recent ($DIFF_DAYS days old)"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add news.json
          
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update news [skip ci]"
          fi

      - name: Push changes
        run: |
          # Получаем последние изменения
          git fetch origin
          
          # Сбрасываем локальные изменения к состоянию origin/main
          git reset --hard origin/main
          
          # Повторно применяем изменения к news.json
          git checkout HEAD -- news.json 2>/dev/null || true
          git add news.json
          
          # Создаем коммит только если есть изменения
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-update news [skip ci]" --allow-empty
          fi
          
          # Прямой push без rebase
          git push origin HEAD:main --force

      - name: Upload debug files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-files
          path: |
            news.json
            error.log
          retention-days: 3
