name: Update Telegram News

on:
  schedule:
    - cron: '0 */4 * * *'  # Каждые 4 часа
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Полная история коммитов
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Fetch Telegram news
        run: node scripts/fetch-news.js

      - name: Commit and push changes
        run: |
          # Настройка git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          
          # Принудительное обновление ветки
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin
          git reset --hard origin/main
          
          # Добавление изменений
          git add news.json
          
          # Проверка изменений и коммит
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Auto-update news [skip ci]"
            # Принудительный push (только для news.json)
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
